name: Docker image build and publish
on:
  workflow_dispatch:
    inputs:
      image_tag:
        description: Tag to apply to images.
        type: string
        default: test

jobs:
  docker:
    runs-on: ubuntu-latest

    permissions:
      id-token: write
      contents: read

    outputs:
      image_tag: ${{ steps.build-publish.outputs.image_tag }}
      full_image: ${{ steps.build-publish.outputs.full_image }}

    steps:
      - uses: actions/checkout@v3

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::216690786812:role/github-actions
          aws-region: "us-east-1"

      - name: Build image
        id: build-publish
        shell: bash
        run: |
          docker build -t rockset/filebeat:latest .

      - name: Login to Amazon ECR (public)
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v2
        with:
          registry-type: public
          aws-region: "us-east-1"
          registries: 216690786812
          mask-password: "true"

      - name: Tag, and push image to Amazon ECR (public)
        id: build-publish
        shell: bash
        env:
          ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
          ECR_REPOSITORY: ${{ github.repository }}
          IMAGE_TAG: ${{ inputs.image_tag }}
        run: |
          docker tag rockset/filebeat:latest public.ecr.aws/r8t4f8i3/rockset/webhook:latest
          docker push public.ecr.aws/r8t4f8i3/rockset/webhook:latest

      - name: Login to Amazon ECR (private)
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v2
        with:
          registry-type: private
          aws-region: "us-east-1"
          registries: 216690786812
          mask-password: "true"

      - name: Tag, and push image to Amazon ECR (private)
        id: build-publish
        shell: bash
        env:
          ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
          ECR_REPOSITORY: ${{ github.repository }}
          IMAGE_TAG: ${{ inputs.image_tag }}
        run: |
          docker tag rockset/filebeat:latest 216690786812.dkr.ecr.us-east-1.amazonaws.com/rockset/webhook:latest
          docker push 216690786812.dkr.ecr.us-east-1.amazonaws.com/rockset/webhook:latest
